version: 2.1

refs:
  only_master: &only_master
    filters:
      branches:
        only: master

orbs:
  artifactory: circleci/artifactory@0.0.7
  build:
    commands:
      determinator:
        parameters:
          paths:
            description: Space seperated list of paths to tests against.
            type: string
        steps:
          - run:
              name: Checking for changes
              command: |
                paths=".circleci <<parameters.paths>>"
                echo "Checking paths [$paths]"
                for path in $paths; do
                  if [[ $(git diff master^ --name-only $path) ]]; then
                    echo "Found changes in $path"
                    exit 0
                  fi
                done
                echo "No changes in [$paths]"
                circleci step halt

commands:
  run-with-retry:
    description: Run command with retry
    parameters:
      command:
        description: Command to run
        type: string
      workdir:
        description: Path to cd into
        type: string
      retry-count:
        description: Number of retry
        type: integer
        default: 3
      sleep:
        description: Wait duration until next retry
        type: integer
        default: 5
    steps:
      - run: |
          retry() {
             MAX_RETRY=<< parameters.retry-count >>
             n=0
             until [ $n -ge $MAX_RETRY ]
             do
                "$@" && break
                n=$[$n+1]
                sleep << parameters.sleep >>
             done
             if [ $n -ge $MAX_RETRY ]; then
               echo "failed: ${@}" >&2
               exit 1
             fi
          }
          cd << parameters.workdir >>
          retry << parameters.command >>

jobs:
  integ-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install OpenVPN
          command: |
            sudo apt-get update
            sudo apt-get install -y openvpn
      - run:
          name: Configure and start VPN client
          command: |
            echo $OVPN_CONF | base64 -d - > ciworker.conf
            sudo mv ciworker.conf /etc/openvpn/client.conf
            sudo service openvpn@client restart
      - run:
          name: Decode SSH private key for worker node
          command: |
            echo $NODE_PKEY | base64 -d - > ci_node.pem
            chmod 0400 ci_node.pem
      - run:
          name: Mock job
          command: |
            ssh -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -i ci_node.pem magma@10.240.0.10 'echo "hello"'

workflows:
  version: 2.1

  magma:
    jobs:
      - integ-test

